```mermaid
flowchart TD
  A[ustvariGui] --> B[ustvariOsnovnoPraznoOkno]
  A --> C[ustvariDropdownPredIzbranihSlik]
  A --> D[prikaziOkno]
  D --> Č[prikaziOkno]
  D --> J[prikaziOkno]





```
TA KOD NI TOK SLABA REALNO
